replicaCount: 1

image:
  repository: chlokesh1306/cve-operator
  tag: latest
  pullPolicy: Always

serviceAccount:
  create: true
  name: ""
namespace: cve-operator-system
rbac:
  create: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
