apiVersion: cve.my.domain/v1
kind: GitHubReleasesMonitor
metadata:
  name: sample-monitor
  namespace: cve-operator-system
spec:
  url: "https://github.com/CVEProject/cvelistV5/releases"
  monitorFrom: "2024-07-19T12:00:00Z"
  monitorTo: "2024-07-26T12:00:00Z"