apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cve-operator.fullname" . }}-manager-role
rules:
- apiGroups:
  - cve.my.domain
  resources:
  - githubreleasesmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cve.my.domain
  resources:
  - githubreleasesmonitors/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cve-operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cve-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "cve-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}